modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/EnvyWare/PixelmonFixes/issues/"

[[mods]]
modId="pixelmonfixes"
version="1.0.3"
displayName="Fixes the Bugs"
displayURL="https://github.com/EnvyWare/PixelmonFixes"
credits="Envyful"
authors="Envyful"
description='''
Envyful
'''
